### ISSUE TITLE
Passport integration

### ISSUE THREAD

**Issue by maxh1231** [maxh1231/tracking-warcraft#3]
- [x] passport package and boilerplate  
- [x] battle.net strategy 
- [x] battle.net oAuth with passport strategy

**Comment by Thenlie** [comment]
🛂 🛂 🛂 I am on it!

**Comment by Thenlie** [comment]
# ✅ Task one complete! 
The basic user authentication functionality has been added as of this evening to the `feature/passport` branch. This includes the local passport strategy and basic login and signup forms. Temporary buttons have been added to the home page to navigate to these pages. Next step will be the battle.net strategy. 🚀 

> NOTE: Most of this logic is copy and paste from the Turtle and MERN Boiler apps.

**Comment by Thenlie** [comment]
# ✅ Task two complete! 

The passport.js Battle.net strategy has been added. Currently working to finalize user oAuth. 🔒

**Comment by Thenlie** [comment]
# ✅ Task three complete! 

PR #7 created

**Comment by Thenlie** [comment]
Closed by #7
